import React from "react";

const DataSourceBadge = ({ source = "System", className = "" }) => {
  const normalized = source === "AI" || source === "ai" ? "AI" : "System";
  return (
    <span
      title={
        normalized === "AI"
          ? "Generated or enriched by AI"
          : "Generated by system rules or stored data"
      }
      className={`ml-1 inline-flex align-baseline text-[10px] font-semibold opacity-70 ${className}`}
    >
      ({normalized})
    </span>
  );
};

export default DataSourceBadge;
