import React from "react";

const DataSourceBadge = ({ source = "SYS", className = "" }) => {
  const normalized =
    source === "AI" || source === "ai" || source === "Ai" ? "AI" : "SYS";
  return (
    <span
      title={
        normalized === "AI"
          ? "Generated or enriched by AI from your metrics"
          : "Generated by system rules from your metrics"
      }
      className={`ml-1 inline-flex align-baseline text-[10px] font-semibold opacity-70 ${className}`}
    >
      ({normalized})
    </span>
  );
};

export default DataSourceBadge;
